### ISSUE TITLE
Upgrade docs are severely lacking

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/shopify-api-ruby#1032] opened 2022-10-05 21:16 UTC
# Issue summary

I'm trying to upgrade to v10, which seems to break literally everything, and the docs are completely inadequate. They basically say "read the new library code and adjust your app accordingly".

## Expected behavior

There should be docs that explicitly state which objects/methods have changed and it should suggest the new syntax to use.

## Actual behavior

Developers are left to fend for themselves.

## Steps to reproduce the problem

1. Have an app that works with v9
2. Upgrade to v10
3. 💥 

## Specifications

- `shopify_api` version: 10
- Shopify API version used (example: `2022-04`):

**Comment by skillmatic-co** [comment] 2022-10-27 16:20
+1, just posted #1049 airing my issues and frustrations as well. I'm just going to downgrade.

**Comment by skillmatic-co** [comment] 2022-10-27 17:12
In the meantime do yourself a favor and:

```
gem 'shopify_app', '< 19.0.0'
gem 'shopify_api', '< 10.0.0'
```

But who knows how long this will last? I wasn't aware upgrading was going to require a complete refactoring of my entire app.

**Comment by EmmaB** [comment] 2022-12-22 14:00
Hard agree.

**Comment by jagthedrummer** [comment] 2023-02-28 02:31
Not stale. This bot sucks.

**Comment by jagthedrummer** [comment] 2023-07-03 15:20
not stale, bot still sucks

**Comment by skillmatic-co** [comment] 2023-07-18 16:43
Still cannot upgrade to v10+ due to these issues.

**Comment by nelsonwittwer** [comment] 2023-08-25 14:15
Improving docs are the top priority of this sprint, especially upgrading to v10. This is a duplicate of #1103 so I'll close this issue and consolidate our discussions there. Thanks for your patience on this!

**Closed by nelsonwittwer** 2023-08-25 14:15 UTC
